language: python
python:
  - "2.7"
  - "3.3"
# command to install dependencies
install:
  - "pip install cython --use-mirrors"
  - "pip install numpy --use-mirrors"
  - "pip install . --use-mirrors"
# command to run tests
script: nosetests
