language: python
env:
  - TEST_SUITE_REGEX='^test_rstan'
  - TEST_SUITE_REGEX='^(?!test_rstan).*'
python:
  - "2.7"
  - "3.3"
# notifications
notifications:
  email:
    recipients:
      - stan-buildbot@googlegroups.com
    on_success: change
    on_failure: always
# command to install dependencies
before_install:
  - sudo apt-get install -qq liblapack-dev gfortran libblas-dev
install:

  - "pip install -q --use-mirrors Cython"
  - "pip install -q --use-mirrors numpy"
  # do not quiet scipy since compiling takes so long; travis-ci assumes there
  # has been an error if no output received in 10m
  - "pip install --use-mirrors scipy"
  - "pip install -q --use-mirrors matplotlib "
  - "pip install ."
# command to run tests
script: nosetests -w /tmp --process-timeout=1200 --processes=2 --exclude=$TEST_SUITE_REGEX pystan.tests
