language: python
env:
  - TEST_SUITE_REGEX='^test_rstan'
  - TEST_SUITE_REGEX='^(?!test_rstan).*'
python:
  - "2.7"
  - "3.3"
# notifications
notifications:
  email:
    recipients:
      - stan-buildbot@googlegroups.com
    on_success: change
    on_failure: always
# command to install dependencies
before_install:
  - sudo apt-get install liblapack-dev gfortran libblas-dev
install:
  - "pip install Cython --use-mirrors"
  - "pip install numpy --use-mirrors"
  - "pip install scipy --use-mirrors"
  - "pip install matplotlib --use-mirrors"
  - "pip install . --use-mirrors"
# command to run tests
script: nosetests -w /tmp --process-timeout=1200 --processes=2 --exclude=$TEST_SUITE_REGEX pystan.tests
