language: python
python:
  - "2.7"
  - "3.3"
# command to install dependencies
install:
  - "python setup.py install"
  - "pip install cython"
  - "pip install numpy"
# command to run tests
script: nosetests
